### ISSUE TITLE
full summary match should ignore the service state

### ISSUE THREAD

**Issue by Bonko** [Jimdo/nagios2trac#11]
an acknowledgement of a service does not match the full summary of a ticket, so it wont append to a "critical problem" ticket after the threshold has been exceeded.

Given a ticket "[wwwXX.example.com] CRITICAL PROBLEM: some_service_check"
and an acknowledge of the service

expected: append to the open ticket because hostname and service description match (eg.: open_ticket_with_same_summary = true)

actual: only a hostname match

**Comment by PirminTapken** [comment]
fixed in 61cee679842a044c34c6f5d998039f54b58f401e
